[tool.poetry]
name = "matrix-analysis"
version = "1.0"
description = "Matrix data export using NumPy, Pandas and Matplotlib"
authors = ["mifranci"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.12.4"
numpy = ">=1.24,<2.0"
pandas = ">=2.2,<3.0"
matplotlib = ">=3.7,<4.0"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"